### ISSUE TITLE
Libvirt box missing after latest update

### ISSUE THREAD

**Issue by richbai90** [ruzickap/packer-templates#370] opened 2022-03-03 02:44 UTC
After today's update d46c1d334815c6cc8ab2403d8294ac284aa1b76c the libvirt box is not available. It redirects to a 404 page. I'm not sure if this is the right place to post this issue, but I would like to use the most recent update if I could.

**Comment by ruzickap** [comment] 2022-03-03 07:18
Thank you for reporting it...
Can you tell me which box it is please?

**Comment by richbai90** [comment] 2022-03-05 07:29
This one:

https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval

**Comment by ruzickap** [comment] 2022-03-05 20:43
I recreated the box - can you check one more time please?

**Comment by marcus905** [comment] 2022-03-16 12:10
Hi,

for all ubuntu desktop boxes in vagrantup the libvirt provider is missimg too.

**Comment by ruzickap** [comment] 2022-03-26 18:55
I know... 
Ubuntu Desktop images are really hard to build using GitHub Actions.
If I build them using the same commands on my Mac / Ubuntu - everything is working fine, but if I do it on Mac instance using GitHub Actions - it failed.
Troubleshooting workloads on GitHub Action Runners is "impossible" :-(

**Comment by abbbi** [comment] 2022-04-13 10:04
same appears to be the case with the 2016 images:

vagrant box update --box peru/windows-server-2016-standard-x64-eval

Checking for updates to 'peru/windows-server-2016-standard-x64-eval'
Latest installed version: 20201108.01
Version constraints: > 20201108.01
Provider: libvirt
Updating 'peru/windows-server-2016-standard-x64-eval' with provider 'libvirt' from version
'20201108.01' to '20220402.01'...
Loading metadata for box 'https://vagrantcloud.com/peru/windows-server-2016-standard-x64-eval'
Adding box 'peru/windows-server-2016-standard-x64-eval' (v20220402.01) for provider: libvirt
Downloading: https://vagrantcloud.com/peru/boxes/windows-server-2016-standard-x64-eval/versions/20220402.01/providers/libvirt.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by CM2Walki** [comment] 2022-05-04 10:57
I have the exact same issue. The `libvirt` provider seems to be missing from all boxes:

Only `virtualbox` is available:
![image](https://user-images.githubusercontent.com/12199415/166668557-a16da581-62d0-47b0-b750-08b2838db2db.png)

https://app.vagrantup.com/peru/boxes/windows-server-2022-standard-x64-eval
https://app.vagrantup.com/peru/boxes/windows-server-2019-standard-x64-eval
https://app.vagrantup.com/peru/boxes/windows-server-2016-standard-x64-eval

```
+ vagrant box add --provider libvirt peru/windows-server-2019-standard-x64-eval
==> box: Loading metadata for box 'peru/windows-server-2019-standard-x64-eval'
    box: URL: https://vagrantcloud.com/peru/windows-server-2019-standard-x64-eval
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: peru/windows-server-2019-standard-x64-eval
Address: https://vagrantcloud.com/peru/windows-server-2019-standard-x64-eval
Requested provider: ["libvirt"]
```

**Comment by ruzickap** [comment] 2022-05-11 20:32
There were some problems with "driver certificates" which should be fixed now.

Can you give it a try?

PetrR

**Closed** 2022-06-12 14:31 UTC
Labels: wontfix
