### ISSUE TITLE
SSH password ?

### ISSUE THREAD

**Issue by HugoPoi** [ruzickap/packer-templates#31] opened 2019-09-24 16:21 UTC
I can't connect with SSH `vagrant ssh` command that's ask for a password obviously `vagrant` but it doesn't work.

Do I need to do something for SSH setup or it work out of the box ?

I used the `peru/my_windows-10-enterprise-x64-eval ` image which have the OpenSSH server but it's not very clear in the documentation.

**Comment by ruzickap** [comment] 2019-09-25 12:20
The problem is caused by the "computername" inside Windows. It's the same as the user you are trying to login: `vagrant`

Here is the description: https://github.com/PowerShell/Win32-OpenSSH/issues/1252

I'll fix it asap...

**Comment by HugoPoi** [comment] 2019-09-25 12:48
Very weird bug so I change the hostname inside Windows as workaround.

**Comment by ruzickap** [comment] 2019-09-25 14:31
Thank you... 
I'll build new images next week where this issue will be fixed...

**Closed** 2019-09-25 14:30 UTC
